name: Build

on:
  push:
  pull_request:

jobs:
  build:
    # This is a *private* build container.
    # See docs/github_actions.md for more information.
    container: ghcr.io/rjkiv/dc3-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Add game versions here
        version: [373307D9]

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Install wine
    - name: Wine
      run: /usr/bin/apt install -y winehq-stable wine-stable wine-stable-i386 wine-stable-amd64
      shell: bash

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      run: |
        python configure.py --dtk assets/dtk.exe --objdiff assets/objdiff-cli.exe --version ${{ matrix.version }} \
            --binutils /binutils --wrapper /usr/bin/wine
        ninja all_source progress build/${{ matrix.version }}/report.json

    # # Upload map files
    # - name: Upload map
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ matrix.version }}_maps
    #     path: build/${{ matrix.version }}/**/*.MAP

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json
